version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "8080:15672"
      - "5672:5672"
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - "rabbitmq"
  db:
    build: ./db
  worker:
    build: ./worker
    depends_on:
      - "rabbitmq"
      - "db"
    restart: on-failure
